awk '
/          profiles\.map\(profile => \(/ {
    print "        ) : activeTab === '"'"'orders'"'"' ? ("
    print "          <div className=\"space-y-4\">"
    print "            {orders.length === 0 ? ("
    print "              <div className=\"py-10 text-center opacity-40\">"
    print "                <ShoppingBag className=\"mx-auto mb-4\" size={32} />"
    print "                <p className=\"text-xs uppercase tracking-widest font-mono\">No Orders Found</p>"
    print "              </div>"
    print "            ) : ("
    print "              orders.map(order => {"
    print "                const orderUser = profiles.find(p => p.id === order.user_id);"
    print "                const userEmail = orderUser ? orderUser.email : \"Guest User\";"
    print "                return ("
    print "                  <div key={order.id} className=\"p-5 bg-surface-container border border-white/5 rounded-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 group hover:border-white/10 transition-colors\">"
    print "                    <div>"
    print "                      <h4 className=\"font-serif text-white leading-tight\">{order.item_name}</h4>"
    print "                      <p className=\"text-[10px] text-white/50 font-mono mt-1\">Order #{order.id?.substring(0,8) || order.payfast_pf_payment_id || \"N/A\"}</p>"
    print "                      <p className=\"text-[11px] text-white/40 mt-1 uppercase tracking-widest\">"
    print "                        Qty: {order.quantity} • Total: R{order.amount_gross}"
    print "                      </p>"
    print "                      <p className=\"text-[10px] text-primary/80 mt-1 uppercase tracking-widest\">"
    print "                        Ordered by: {userEmail}"
    print "                      </p>"
    print "                    </div>"
    print "                    <div className=\"flex items-center gap-3\">"
    print "                      <span className={cn("
    print "                        \"px-2.5 py-1 rounded-lg text-[9px] font-extrabold uppercase tracking-widest border\","
    print "                        order.status === '"'"'complete'"'"' ? \"border-green-500/30 text-green-400 bg-green-500/10\" :"
    print "                        order.status === '"'"'pending'"'"' ? \"border-yellow-500/30 text-yellow-400 bg-yellow-500/10\" :"
    print "                        \"border-white/20 text-white/50 bg-white/5\""
    print "                      )}>"
    print "                        {order.status}"
    print "                      </span>"
    print "                    </div>"
    print "                  </div>"
    print "                );"
    print "              })"
    print "            )}"
    print "          </div>"
    print "        ) : ("
}
{ print }
' src/components/AdminSection.tsx > tmp.tsx && mv tmp.tsx src/components/AdminSection.tsx
